### PR TITLE
Move Url and Signer classes into libthumbor

### LINKED ISSUE #24: Url and Signer should be part of libthumbor
I can take care of the move, but first I want a second opinion to check that my logic is correct.

Currently, the libthumbor tests depend on thumbor, but that dependency is implicit. Specifically, tests/test_libthumbor.py imports Signer from thumbor.crypto and Url from thumbor.url

This creates an annoying circular dependency which makes packaging libthumbor difficult.

However, Signer and Url are both standalone classes. Therefore they look easy to move to libthumbor. By doing so, there would be a much cleaner separation between both modules and packaging of libthumbor would become easier.

Does this move make sense?

### PR DESCRIPTION
**Pull request by gi11es**
Fixes #24

Removes dependency on Thumbor.
Bumps version.

### CODE REVIEW

**Comment by gi11es** [comment]
Not sure if the git tag will work as part of the PR. Might need to be recreated on this repo?

**Comment by guilhermef** [comment]
Looks really good.
What do you think @heynemann ?

**Comment by heynemann** [comment]
Why do you think this is needed @gi11es? We added the dependency on thumbor, so we have this code in one place only, thus not needing to update it in two different places.

The reason behind this is debian packaging?

**Comment by guilhermef** [comment]
@heynemann Thumbor already depends on libthumbor to generate url's using the CLI.

**Comment by gi11es** [comment]
Yes, this came from a need to simplify debian packaging. The idea is to have this code only here in libthumbor, and remove it from Thumbor. I need this merged first before I can make a working PR on Thumbor to remove the code there. Otherwise if I attempt to remove the code from Thumbor now, it's just going to fail tests because it's not in libthumbor yet.

This way libthumbor will be truly independent again. Lighter to test, build, package, etc. And this code only lives in one place. Note that the code was already duplicated here for Python 3 (and outdated, unsurprisingly) and with my change this sort of issue will go away.

**Comment by heynemann** [comment]
Ok, I'm fine with this PR if we remove this code from thumbor. Thanks a lot for the effort @gi11es. We really appreciate it.

**Comment by gi11es** [comment]
You guys need to create the 3.1.2 git tag: https://github.com/thumbor/libthumbor/tags The PR merge didn't carry that over.

**Comment by guilhermef** [comment]
Done @gi11es https://pypi.python.org/pypi/libthumbor/1.3.2, sorry about that.

**Pull request merged**
