### PR TITLE
Support for Python3 and Django 1.7

### PR DESCRIPTION
**Pull request by morenosan**
Hi,

I added Python 3 support in libthumbor using six. Tests should pass for Python 2.7 and 3.4.
I know it's suboptimal, but right now, Thumbor doesn't support Python 3, so to pass the unit tests in Python 3.4, I also ported the url and crypto modules from Thumbor and added them to the test directory.
Finally, I modified the setup script to add the six dependency.

Hope you find it useful.

### CODE REVIEW

**Comment by elliottsj** [comment]
Can we get this PR merged? @scorphus?

@morenosan: Are you able to resolve the conflicts & fix the build? I'm willing to do it if you don't have the time :smile:

**Comment by morenosan** [comment]
From the log of Travis, I saw the source of the error was a network error trying to download http://python-distribute.org/distribute_setup.py during the creation of the test environment.
Is there any way to relaunch the build?

**Comment by elliottsj** [comment]
Yeah, looks like http://python-distribute.org/ no longer exists :confused: 

@morenosan If you add a commit to your branch (or edit an existing one) and push, Travis should rebuild.

**Comment by guilhermef** [comment]
@morenosan can you rebase your PR ?

**Comment by morenosan** [comment]
@guilhermef Rebase done

**Comment by heynemann** [comment]
GJ on this PR.

**Comment by elliottsj** [comment]
:+1:

**Pull request merged**
